-- Generated by Noctalia Shell - Do not edit manually
local M = {}

M.colors = {
  background = "{{colors.surface.default.hex}}",
  foreground = "{{colors.on_surface.default.hex}}",
  primary = "{{colors.primary.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  on_secondary = "{{colors.on_secondary.default.hex}}",
  error = "{{colors.error.default.hex}}",
}

return M
