cursor #bfc2ff
cursor_text_color #131316

foreground            #e5e1e6
background            #131316
selection_foreground  #131316
selection_background  #bfc2ff
url_color             #c5c4dd

# Black
color0   #131316
color8   #131316

# Red
color1   #ffb4ab
color9   #ffb4ab

# Green
color2   #c5c4dd
color10  #c5c4dd

# Yellow
color3   #e8b9d5
color11  #e8b9d5

# Blue
color4   #bfc2ff
color12  #bfc2ff

# Magenta
color5   #e8b9d5
color13  #e8b9d5

# Cyan
color6   #c5c4dd
color14  #c5c4dd

# White
color7   #e5e1e6
color15  #e5e1e6
