[main]
font=JetBrainsMono Nerd Font:size=12
prompt="󰍉  "
terminal=kitty
width=35
horizontal-pad=25
vertical-pad=20
inner-pad=10

# Matches your Niri corner radius
border-radius=20
border-width=2

[colors]
# Background: Noctalia Dark Grey at 90% opacity
background=11111be6
# Text: Soft White
text=cdd6f4ff
# Prompt: Lavender
prompt=b4beefff
# Placeholder text
placeholder=7f849cff
# Selection background: Lavender (Low Opacity)
selection=b4beef40
# Selection text: Bright White
selection-text=f5e0dcff
# Border: Lavender (Matches Noctalia accents)
border=b4beefff
# Match characters (while typing): Lavender
match=b4beefff
selection-match=b4beefff

[border]
width=2
radius=20
